### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by aviraxp** [afxefx/InstallerOpt#12]
logcat flooding with this

07-09 23:36:20.297 D/Settings(14455): Have 0 number of activities in preferred list
07-09 23:36:20.424 W/ContextImpl(14455): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:773 de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative:-2 de.robv.android.xposed.XposedBridge.handleHookedMethod:334 android.app.ContextImpl.sendBroadcast:-1 android.content.ContextWrapper.sendBroadcast:402 

after I view one app’s app information.

**Comment by afxefx** [comment]
Can you provide a bit log please?

**Comment by aviraxp** [comment]
[2016-07-09-23-46-47.txt](https://github.com/afxefx/InstallerOpt/files/355628/2016-07-09-23-46-47.txt)

**Comment by afxefx** [comment]
One more request, can you enable debug in the module and post a logcat and the xposed log also?

**Comment by aviraxp** [comment]
[2016-07-10-00-06-19.txt](https://github.com/afxefx/InstallerOpt/files/355636/2016-07-10-00-06-19.txt)
[xposed_error_20160710_000313.txt](https://github.com/afxefx/InstallerOpt/files/355637/xposed_error_20160710_000313.txt)

**Comment by aviraxp** [comment]
seems it only happens when the force stop button is grey.

**Comment by aviraxp** [comment]
It is CM’s fault. It has been fixed in July 8.
http://review.cyanogenmod.org/#/c/151864
