### ISSUE TITLE
many options in privacy management missing after turning on disable signature check

### ISSUE THREAD

**Issue by aviraxp** [afxefx/InstallerOpt#14]

**Comment by aviraxp** [comment]
details will be explained later.

**Comment by aviraxp** [comment]
before![screenshot_20160710-232040](https://cloud.githubusercontent.com/assets/18079988/16714433/78db77dc-4688-11e6-8bad-417f22d2c6d8.png)
after![screenshot_20160710-232031](https://cloud.githubusercontent.com/assets/18079988/16714435/7efba86c-4688-11e6-83bb-aedf0e8b0b7a.png)

**Comment by aviraxp** [comment]
[xposed_error_20160710_232309.txt](https://github.com/afxefx/InstallerOpt/files/356082/xposed_error_20160710_232309.txt)
[2016-07-10-23-23-48.txt](https://github.com/afxefx/InstallerOpt/files/356083/2016-07-10-23-23-48.txt)

**Comment by afxefx** [comment]
That's what I needed to see as I'm not running a ROM with those options, I'll see what I can do and send you a test version.

**Comment by aviraxp** [comment]
I think it a quite serious issue……cause many people are using CM13.

**Comment by afxefx** [comment]
I agree completely and have moved it to the top of my work list.

**Comment by aviraxp** [comment]
Hey bro, have you made some progress on it these days?
Besides, I would like to translate it into Chinese, but I see that there are some differences between /value/strings.xml and/value-sk/strings.xml, I wonder which one I should use for translation.

**Comment by afxefx** [comment]
I'm still researching the issue and hope to have some results by the end of the week.  In regards to the translation use the strings.xml file as that is the one I create in English, but they should match now.  Ja_som had fixed some hardcoded strings I missed but I hadn't synced my repo yet.

**Comment by pylerSM** [comment]
https://github.com/CyanogenMod/android_packages_apps_Settings/blob/467fae0d11044f3642779ae8dfdd1172c8ea3161/src/com/android/settings/applications/AppOpsDetails.java#L108

**Comment by aviraxp** [comment]
So this is a CM issue. But I think we can just hook it, 

```
    private boolean isPlatformSigned() {
        final int match = mPm.checkSignatures("android", mPackageInfo.packageName);
        return match >= PackageManager.SIGNATURE_MATCH;
    }
```

just return true

**Comment by pylerSM** [comment]
Return false..

**Comment by aviraxp** [comment]
my fault

**Comment by afxefx** [comment]
aviraxp, I'm not currently running CM so would you mind testing this version and let me know if it's resolved?

http://www.fypm.net/xposed/net.fypm.InstallerOpt1.0.6%20%28209%29%201220-debug.apk

**Comment by aviraxp** [comment]
Sure, I will tell you the result in a day since I am not at phone.

**Comment by aviraxp** [comment]
works it seems
