### ISSUE TITLE
Signature check option to install same app version with different signature doesn't work

### ISSUE THREAD

**Issue by tecufanujacu** [afxefx/InstallerOpt#18]
As reported in the xda thread in the post [#344](http://forum.xda-developers.com/showpost.php?p=67968159&postcount=344) the signature check option to install same app version with different signature doesn't work, I tried install Signal on LibreSignal(same app with only different name and signature) without success.

Is this a known issue?

**Comment by afxefx** [comment]
It is, I just haven't had any free time to actually resolve it.  It's on my list though.

**Comment by Maxr1998** [comment]
It seems that the method [verifySignaturesLP](https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/pm/PackageManagerService.java#7144) returns void, but you set the result to "true" in your hook. Additionally, you should check the `disableCheckSignatures` variable.

**Comment by afxefx** [comment]
This should be resolved now hopefully.
