### ISSUE TITLE
version 1.0.7 (2) bootloop

### ISSUE THREAD

**Issue by MacgyverJohnson** [afxefx/InstallerOpt#27]
Hi there @afxefx 
And I thought i was the only one getting the bootloop....had just updated to latest version(1.0.7 (2)) but also updated 1 other xposed and installed 1 new xposed module but they always have been working for a long time so i dont think they were the issue...didnt want to restore from nandroid backup so sideloaded xposed uninstaller instead...which logs do u need dev?
Could it be that signature verification which was turned on another xposed module could have been the culprit here?
Thanks

**Comment by afxefx** [comment]
A logcat and the xposed log would be great.  Two apps attempting signature modifications could definitely be the culprit.

**Comment by MacgyverJohnson** [comment]
Hi there @afxefx 
Disabled the "so called'' culprit's xposed module but still faced bootloop just after activating InstallerOpt module and doing soft reboot(I always soft reboot after installing/updating/uninstalling xposed modules...is that a bad thing?)...about xposed logs I went to data>data>de.robv.xposed.installer>log........reverted back to older version for now........{I logged two times )  
Thanks 
[log.zip](https://github.com/afxefx/InstallerOpt/files/466944/log.zip)

**Comment by afxefx** [comment]
Can you try this version please and thank you.

[http://www.fypm.net/xposed/net.fypm.InstallerOpt1.0.7%20%2817%29%201242-debug.apk](url)

**Comment by MacgyverJohnson** [comment]
Bootloop all overagain...........everything checked except signature verification and unsigned apps-->working. whenever those two are checked and rebooted--> bootloop....cant give catlogs before 20 hours but I can manage xposed logs

**Comment by afxefx** [comment]
Would you mind giving this one a go and reporting back?

[http://www.fypm.net/xposed/net.fypm.InstallerOpt1.0.7%20%2820%29%201245-debug.apk](url)

**Comment by MacgyverJohnson** [comment]
This version at first installation(with soft reboot) disabled the xposed framework.....so i uninstalled and installed and reboooted(not soft reboot) this time no bootloops :) but checking xposed logs signatur verification does not start...xposed logs attached(could u attach two apk file one original another unmodified so that i can check? logs contain older logs as well check recent ones
[Download_2.zip](https://github.com/afxefx/InstallerOpt/files/467952/Download_2.zip)

**Comment by afxefx** [comment]
I've been using the following two for testing and the initial statement in the log about checking may not be accurate atm

https://www.dropbox.com/s/o902x9y11zm2ba3/SIGN1.apk?dl=0

https://www.dropbox.com/s/m65q9opt42lvivt/SIGN2.apk?dl=0

**Comment by MacgyverJohnson** [comment]
these apps were installed on top of another (upgraded) without any issues..does that mean its working?

**Comment by MacgyverJohnson** [comment]
yes disabling signature checks and app verification shows error code-7 so i guess now its working..thanks for all the effort dev @afxefx
