### ISSUE TITLE
Mokee Support

### ISSUE THREAD

**Issue by aviraxp** [afxefx/InstallerOpt#3]
I am running Mokee based on CM, which is a popular rom in China. Since it change the name of packageinstaller to com.mokee.packageinstaller, most of the moudle does not work. Could you add support for it?

**Comment by afxefx** [comment]
Added this today but let me know if it works for you, I'll update the xposed repo at some point today.

**Comment by afxefx** [comment]
Any update on whether it's working for you now?

**Comment by aviraxp** [comment]
Working now. Thanks a lot.
