### ISSUE TITLE
All user apps do not show in launcher after activating the moudle

### ISSUE THREAD

**Issue by aviraxp** [afxefx/InstallerOpt#30]
Many users in China reported this, one said that after changing the status of 'show app icon' it fixed. 1.0.6 is ok.

I am attempting to collect logs. Very thanks for your work.

**Comment by afxefx** [comment]
Those logs would be awesome and appreciate your help greatly.

**Comment by afxefx** [comment]
Can you try this version please and thank you:

[http://www.fypm.net/xposed/net.fypm.InstallerOpt1.0.7%20%2820%29%201245-debug.apk](url)

**Comment by aviraxp** [comment]
Fixed.
